package com.rongli.driver.rlxx.hiswebs;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * HisServiceImpService service = new HisServiceImpService();
 * HisService portType = service.getHisServiceImpPort();
 * portType.sayHiDefault(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "HisServiceImpService", targetNamespace = "http://imp.jaxws.yj.com/", wsdlLocation = "http://www.powerbok.com/RLWebService/service/dotrade?wsdl")
public class HisServiceImpService extends Service {

	private final static URL HISSERVICEIMPSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(HisServiceImpService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = HisServiceImpService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://www.powerbok.com/RLWebService/service/dotrade?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://www.powerbok.com/RLWebService/service/dotrade?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		HISSERVICEIMPSERVICE_WSDL_LOCATION = url;
	}

	public HisServiceImpService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public HisServiceImpService() {
		super(HISSERVICEIMPSERVICE_WSDL_LOCATION, new QName(
				"http://imp.jaxws.yj.com/", "HisServiceImpService"));
	}

	/**
	 * 
	 * @return returns HisService
	 */
	@WebEndpoint(name = "HisServiceImpPort")
	public HisService getHisServiceImpPort() {
		return super.getPort(new QName("http://imp.jaxws.yj.com/",
				"HisServiceImpPort"), HisService.class);
	}

}
